name: Code Agent Workflow

# usage 
# export BRANCH_NAME=$(gh pr list --json headRefName --jq '.[].headRefName')
# gh workflow run code-agent.yml --ref $BRANCH_NAME
 
on:
  workflow_dispatch:

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start ChromaDB Service
        run: |
          nohup chromadb-server &

      - name: Run Agent with ChromaDB
        run: python code-agent.py
        working-directory: agents
        env:
          CHROMADB_HOST: localhost
          CHROMADB_PORT: 8000
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}