name: Run Tests on PR

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  test:
    if: github.head_ref != '8-pull-request-agent'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test
